package assets

// LegacyIconMappings maps the old icon IDs to the new filenames.
var LegacyIconMappings = map[string]string{
	"1":  "grass",
	"2":  "diamond",
	"3":  "sword_diamond",
	"4":  "creeper",
	"5":  "pig",
	"6":  "tnt",
	"7":  "cookie",
	"8":  "heart",
	"9":  "bed",
	"10": "cake",
	"11": "sign",
	"12": "rail",
	"13": "crafting_table",
	"14": "redstone",
	"15": "fire",
	"16": "cobweb",
	"17": "chest",
	"18": "furnace",
	"19": "book",
	"20": "stone",
	"21": "planks",
	"22": "iron",
	"23": "gold",
	"24": "door_wood",
	"25": "door_iron",
	"26": "chestplate_diamond",
	"27": "flint_and_steel",
	"28": "potion",
	"29": "splash_potion",
	"30": "spawn_egg",
	"31": "coal",
	"32": "sword_iron",
	"33": "bow",
	"34": "arrow",
	"35": "chestplate_iron",
	"36": "bucket",
	"37": "bucket_water",
	"38": "bucket_lava",
	"39": "bucket_milk",
}
